import RieszEuclidean.Basic
import RieszEuclidean.ProjectionGap
import RieszEuclidean.MovingComparison

import RieszEuclidean.WeakLimits
import RieszEuclidean.L2Transport
import RieszEuclidean.Affine
import RieszEuclidean.FourierL2
