import Mathlib.Analysis.Calculus.BumpFunction.SmoothApprox
import Mathlib.Analysis.Distribution.FourierSchwartz
import Mathlib.Analysis.InnerProductSpace.Adjoint
import Mathlib.Analysis.InnerProductSpace.PiL2
import Mathlib.Analysis.InnerProductSpace.l2Space
import Mathlib.Analysis.Normed.Operator.Banach
import Mathlib.Analysis.Normed.Operator.BoundedLinearMaps
import Mathlib.Analysis.NormedSpace.OperatorNorm.Completeness
import Mathlib.Analysis.SpecialFunctions.Exponential
import Mathlib.Analysis.SpecificLimits.Normed
import Mathlib.LinearAlgebra.FiniteDimensional.Lemmas
import Mathlib.MeasureTheory.Function.ContinuousMapDense
import Mathlib.MeasureTheory.Function.ConvergenceInMeasure
import Mathlib.MeasureTheory.Function.L2Space
import Mathlib.MeasureTheory.Measure.Haar.InnerProductSpace
import Mathlib.MeasureTheory.Measure.Lebesgue.EqHaar
import Mathlib.Tactic.Abel
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.Positivity

/-!
# Standalone Euclidean formalization: implemented components

Generated by scripts/build_standalone.py. No project import is required.
The geometric nonexistence theorems remain pending; MainResults specifies only
the currently proved foundational and affine results. This file is a complete
proof of those statements, not of the entire manuscript.
-/

/- Source: RieszEuclidean/Basic.lean -/
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
/-!
# Concrete Euclidean synthesis semantics

The Fourier convention is exp(2 π i ⟪ξ,x⟫), as in `paper/RieszEuclidean.tex`.
Mathlib's inner product is conjugate-linear in its first argument.
No lattice or quotient space is part of these definitions.
-/
noncomputable section
open MeasureTheory
open scoped ENNReal
namespace RieszEuclidean

/-- Finite-dimensional Euclidean space with its standard inner product and Lebesgue measure. -/
abbrev Euclidean (d : ℕ) := EuclideanSpace ℝ (Fin d)
/-- The coefficient Hilbert space of square-summable complex families. -/
abbrev SeqL2 (ι : Type) := lp (fun _ : ι => ℂ) 2
/-- Complex L² for Lebesgue measure restricted to the actual domain. -/
abbrev DomainL2 {d : ℕ} (Ω : Set (Euclidean d)) := Lp ℂ 2 (volume.restrict Ω)

/-- The paper's exponential with the positive 2π Fourier convention. -/
def exponential {d : ℕ} (ξ x : Euclidean d) : ℂ :=
  Complex.exp (2 * (Real.pi : ℂ) * Complex.I * (inner (𝕜 := ℝ) ξ x : ℂ))

/-- A boundedly invertible synthesis map with its actual exponential columns. -/
def HasExponentialRieszBasis {d : ℕ} (Ω Λ : Set (Euclidean d)) : Prop := by
  classical
  exact ∃ S : SeqL2 Λ ≃L[ℂ] DomainL2 Ω,
    ∀ ξ : Λ, (S (lp.single 2 ξ 1) : Euclidean d → ℂ) =ᵐ[volume.restrict Ω]
      exponential ξ.val

/-- Configuration action T_y Γ = Γ - y. -/
def translate {d : ℕ} (y : Euclidean d) (Γ : Set (Euclidean d)) : Set (Euclidean d) :=
  {x | x + y ∈ Γ}

@[simp] theorem mem_translate {d : ℕ} (y x : Euclidean d) (Γ : Set (Euclidean d)) :
    x ∈ translate y Γ ↔ x + y ∈ Γ := Iff.rfl

@[simp] theorem translate_zero {d : ℕ} (Γ : Set (Euclidean d)) : translate 0 Γ = Γ := by
  ext x
  simp [translate]

@[simp] theorem translate_add {d : ℕ} (y z : Euclidean d) (Γ : Set (Euclidean d)) :
    translate y (translate z Γ) = translate (y + z) Γ := by
  ext x
  simp [translate, add_assoc]

/-- Uniform separation with a specified lower bound. -/
def Separated {d : ℕ} (δ : ℝ) (Γ : Set (Euclidean d)) : Prop :=
  ∀ ⦃x⦄, x ∈ Γ → ∀ ⦃y⦄, y ∈ Γ → x ≠ y → δ ≤ dist x y

/-- Beurling's local matching definition, with centers remaining in Euclidean space. -/
def WeaklyConverges {d : ℕ} (Γ : ℕ → Set (Euclidean d)) (Γ₀ : Set (Euclidean d)) : Prop :=
  ∀ R : ℝ, 0 < R → ∀ ε : ℝ, 0 < ε → ∃ N : ℕ, ∀ j ≥ N,
    (∀ x ∈ Γ j, ‖x‖ < R → ∃ y ∈ Γ₀, dist x y < ε) ∧
    (∀ y ∈ Γ₀, ‖y‖ < R → ∃ x ∈ Γ j, dist x y < ε)

/-- An arbitrary invertible affine image of a Euclidean ball. -/
def affineBall {d : ℕ} (a : Euclidean d) (A : Euclidean d ≃L[ℝ] Euclidean d)
    (R : ℝ) : Set (Euclidean d) :=
  (fun x => a + A x) '' Metric.ball 0 R

end RieszEuclidean

/- Source: RieszEuclidean/L2Transport.lean -/
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
/-! General L² pullback and unit-phase reindexing, extracted from the old
BallRounding module. No frequency rounding is imported or performed here. -/
noncomputable section
open MeasureTheory MeasureTheory.Measure Filter Topology
open scoped ENNReal
namespace RieszEuclidean

section Pullback
variable {α β : Type} [MeasurableSpace α] [MeasurableSpace β]
  {μ : Measure α} {ν : Measure β} {c : ℝ≥0∞}
  (f : α → β) (hf : Measurable f) (hmap : Measure.map f μ = c • ν) (hc : c ≠ ∞)

/-- The a.e. pullback of an L² function under a map with finite constant Jacobian. -/
def scaledL2PullbackValue (g : Lp ℂ 2 ν) : Lp ℂ 2 μ :=
  (((Lp.memLp g).smul_measure hc).comp_measurePreserving ⟨hf, hmap⟩).toLp (g ∘ f)

theorem scaledL2PullbackValue_ae (g : Lp ℂ 2 ν) :
    (scaledL2PullbackValue f hf hmap hc g : α → ℂ) =ᵐ[μ] g ∘ f :=
  MemLp.coeFn_toLp _

theorem scaledL2PullbackValue_norm (g : Lp ℂ 2 ν) :
    ‖scaledL2PullbackValue f hf hmap hc g‖ = (c ^ (1 / (2 : ℝ≥0∞)).toReal).toReal * ‖g‖ := by
  rw [scaledL2PullbackValue, Lp.norm_toLp,
    eLpNorm_comp_measurePreserving ((Lp.memLp g).smul_measure hc).1 ⟨hf, hmap⟩,
    eLpNorm_smul_measure_of_ne_top (by norm_num : (2 : ℝ≥0∞) ≠ ∞)]
  rw [smul_eq_mul, ENNReal.toReal_mul, Lp.norm_def]

/-- Pullback assembled as a complex linear map on L² equivalence classes. -/
def scaledL2PullbackLinear : Lp ℂ 2 ν →ₗ[ℂ] Lp ℂ 2 μ where
  toFun := scaledL2PullbackValue f hf hmap hc
  map_add' g k := by
    have hq : QuasiMeasurePreserving f μ ν := ⟨hf, by rw [hmap]; exact smul_absolutelyContinuous⟩
    apply Lp.ext
    filter_upwards [scaledL2PullbackValue_ae f hf hmap hc (g + k), scaledL2PullbackValue_ae f hf hmap hc g,
      scaledL2PullbackValue_ae f hf hmap hc k, hq.ae (Lp.coeFn_add g k),
      Lp.coeFn_add (scaledL2PullbackValue f hf hmap hc g) (scaledL2PullbackValue f hf hmap hc k)] with x h1 h2 h3 h4 h5
    simp only [Pi.add_apply, Function.comp_apply] at h1 h2 h3 h4 h5
    exact h1.trans (h4.trans (by rw [h5, h2, h3]))
  map_smul' z g := by
    have hq : QuasiMeasurePreserving f μ ν := ⟨hf, by rw [hmap]; exact smul_absolutelyContinuous⟩
    apply Lp.ext
    filter_upwards [scaledL2PullbackValue_ae f hf hmap hc (z • g), scaledL2PullbackValue_ae f hf hmap hc g,
      hq.ae (Lp.coeFn_smul z g), Lp.coeFn_smul z (scaledL2PullbackValue f hf hmap hc g)] with x h1 h2 h3 h4
    change _ = (z • scaledL2PullbackValue f hf hmap hc g) x
    simp only [Pi.smul_apply, Function.comp_apply] at h1 h2 h3 h4
    exact h1.trans (h3.trans (by rw [h4, h2]))

/-- Pullback along a measurable map with a finite constant measure Jacobian. -/
def scaledL2Pullback : Lp ℂ 2 ν →L[ℂ] Lp ℂ 2 μ :=
  (scaledL2PullbackLinear f hf hmap hc).mkContinuous (c ^ (1 / (2 : ℝ≥0∞)).toReal).toReal
    (fun g => (scaledL2PullbackValue_norm f hf hmap hc g).le)

theorem scaledL2Pullback_ae (g : Lp ℂ 2 ν) :
    (scaledL2Pullback f hf hmap hc g : α → ℂ) =ᵐ[μ] g ∘ f :=
  scaledL2PullbackValue_ae f hf hmap hc g

end Pullback

section Equiv
variable {α β : Type} [MeasurableSpace α] [MeasurableSpace β]
  {μ : Measure α} {ν : Measure β} {c : ℝ≥0∞}
  (e : α ≃ᵐ β) (hmap : Measure.map e μ = c • ν) (hc0 : c ≠ 0) (hc : c ≠ ∞)

include hmap hc0 hc in
theorem scaledL2Equiv_inverse_map : Measure.map e.symm ν = c⁻¹ • μ := by
  have h := e.map_symm_map (μ := μ)
  rw [hmap, Measure.map_smul] at h
  rw [← h, smul_smul, ENNReal.inv_mul_cancel hc0 hc, one_smul]

/-- A measurable equivalence with nonzero finite constant Jacobian induces an L² equivalence. -/
def scaledL2Equiv : Lp ℂ 2 ν ≃L[ℂ] Lp ℂ 2 μ := by
  let p := scaledL2Pullback e e.measurable hmap hc
  let q := scaledL2Pullback e.symm e.symm.measurable (scaledL2Equiv_inverse_map e hmap hc0 hc)
    (ENNReal.inv_ne_top.mpr hc0)
  have hp (g : Lp ℂ 2 ν) : (p g : α → ℂ) =ᵐ[μ] g ∘ e :=
    scaledL2Pullback_ae _ _ _ _ g
  have hq (g : Lp ℂ 2 μ) : (q g : β → ℂ) =ᵐ[ν] g ∘ e.symm :=
    scaledL2Pullback_ae _ _ _ _ g
  have hep : QuasiMeasurePreserving e μ ν :=
    ⟨e.measurable, by rw [hmap]; exact smul_absolutelyContinuous⟩
  have heq : QuasiMeasurePreserving e.symm ν μ :=
    ⟨e.symm.measurable, by rw [scaledL2Equiv_inverse_map e hmap hc0 hc]; exact smul_absolutelyContinuous⟩
  exact
    { toLinearEquiv :=
        { p.toLinearMap with
          invFun := q
          left_inv := fun g => Lp.ext (by
            filter_upwards [hq (p g), heq.ae (hp g)] with x hx hy
            simpa only [Function.comp_apply, e.apply_symm_apply] using hx.trans hy)
          right_inv := fun g => Lp.ext (by
            filter_upwards [hp (q g), hep.ae (hq g)] with x hx hy
            simpa only [Function.comp_apply, e.symm_apply_apply] using hx.trans hy) }
      continuous_toFun := p.continuous
      continuous_invFun := q.continuous }

theorem scaledL2Equiv_ae (g : Lp ℂ 2 ν) :
    (scaledL2Equiv e hmap hc0 hc g : α → ℂ) =ᵐ[μ] g ∘ e :=
  scaledL2Pullback_ae _ _ _ _ g

end Equiv

section Sequences
variable {ι κ : Type} (e : ι ≃ κ) (w : ι → ℂ) (hw : ∀ i, ‖w i‖ = 1)

/-- Reindex a square-summable family and multiply its coordinates by unit phases. -/
def weightedReindexValue (g : SeqL2 κ) : SeqL2 ι :=
  ⟨fun i => w i * g (e i), memℓp_gen (by
    simpa only [norm_mul, hw, one_mul] using
      e.summable_iff.mpr ((lp.memℓp g).summable (by norm_num)))⟩

/-- Reindexing and unit-modulus phases preserve the coefficient Hilbert norm. -/
def weightedReindex : SeqL2 κ ≃ₗᵢ[ℂ] SeqL2 ι where
  toFun := weightedReindexValue e w hw
  invFun := weightedReindexValue e.symm (fun k => (w (e.symm k))⁻¹) (by simp [hw])
  map_add' g k := by ext i; exact mul_add _ _ _
  map_smul' z g := by ext i; exact mul_left_comm _ _ _
  left_inv g := by
    ext k
    change (w (e.symm k))⁻¹ * (w (e.symm k) * g (e (e.symm k))) = g k
    rw [e.apply_symm_apply, ← mul_assoc, inv_mul_cancel₀, one_mul]
    exact norm_ne_zero_iff.mp (by rw [hw]; norm_num)
  right_inv g := by
    ext i
    change w i * ((w (e.symm (e i)))⁻¹ * g (e.symm (e i))) = g i
    rw [e.symm_apply_apply, ← mul_assoc, mul_inv_cancel₀, one_mul]
    exact norm_ne_zero_iff.mp (by rw [hw]; norm_num)
  norm_map' g := by
    rw [lp.norm_eq_tsum_rpow (by norm_num), lp.norm_eq_tsum_rpow (by norm_num)]
    congr 1
    change (∑' i, ‖w i * g (e i)‖ ^ (2 : ℝ≥0∞).toReal) = _
    simp only [norm_mul, hw, one_mul]
    exact e.tsum_eq (fun k => ‖g k‖ ^ (2 : ℝ≥0∞).toReal)

theorem weightedReindex_apply (g : SeqL2 κ) (i : ι) :
    weightedReindex e w hw g i = w i * g (e i) := rfl

theorem weightedReindex_single [DecidableEq ι] [DecidableEq κ] (i : ι) :
    weightedReindex e w hw (lp.single 2 (e i) 1) = w i • lp.single 2 i 1 := by
  classical
  ext j
  simp only [weightedReindex_apply, lp.coeFn_smul, Pi.smul_apply, smul_eq_mul]
  by_cases h : j = i
  · subst j; simp
  · simp [lp.single_apply, h, e.injective.ne h]

end Sequences


end RieszEuclidean

/- Source: RieszEuclidean/Affine.lean -/
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
/-! Invertible affine changes of domain and the transpose change of frequencies. -/

noncomputable section
open MeasureTheory MeasureTheory.Measure Filter Topology
open scoped ENNReal

namespace RieszEuclidean

variable {d : ℕ}

/-- An invertible affine coordinate map in the current Euclidean dimension. -/
def planeAffine (a : (Euclidean d)) (A : (Euclidean d) ≃L[ℝ] (Euclidean d)) : (Euclidean d) ≃ᵐ (Euclidean d) where
  toFun x := a + A x
  invFun x := A.symm (x - a)
  left_inv x := by simp
  right_inv x := by simp
  measurable_toFun := measurable_const.add A.continuous.measurable
  measurable_invFun := A.symm.continuous.measurable.comp (measurable_id.sub measurable_const)

/-- The inverse absolute determinant, which is the Jacobian for pushforward. -/
def affineJacobian (A : (Euclidean d) ≃L[ℝ] (Euclidean d)) : ℝ≥0∞ :=
  ENNReal.ofReal |(LinearMap.det A.toLinearEquiv.toLinearMap)⁻¹|

theorem affineJacobian_ne_zero (A : (Euclidean d) ≃L[ℝ] (Euclidean d)) : affineJacobian A ≠ 0 := by
  apply ENNReal.ofReal_ne_zero_iff.mpr
  exact abs_pos.mpr (inv_ne_zero (A.toLinearEquiv.isUnit_det'.ne_zero))

theorem affineJacobian_ne_top (A : (Euclidean d) ≃L[ℝ] (Euclidean d)) : affineJacobian A ≠ ∞ :=
  ENNReal.ofReal_ne_top

/-- The full change-of-variables formula, including translation and arbitrary determinant. -/
theorem planeAffine_map (a : (Euclidean d)) (A : (Euclidean d) ≃L[ℝ] (Euclidean d)) (D : Set (Euclidean d)) :
    Measure.map (planeAffine a A) (volume.restrict D) =
      affineJacobian A • volume.restrict ((planeAffine a A) '' D) := by
  have hm : Measure.map (planeAffine a A) volume =
      affineJacobian A • (volume : Measure (Euclidean d)) := by
    change Measure.map ((fun x : (Euclidean d) => a + x) ∘ A) volume = _
    have hma : Measurable (fun x : (Euclidean d) => a + x) := measurable_const.add measurable_id
    rw [← Measure.map_map hma A.continuous.measurable]
    have hA : Measure.map A (volume : Measure (Euclidean d)) = affineJacobian A • volume :=
      map_linearMap_addHaar_eq_smul_addHaar volume A.toLinearEquiv.isUnit_det'.ne_zero
    rw [hA, Measure.map_smul, map_add_left_eq_self]
  have hpre : (planeAffine a A) ⁻¹' ((planeAffine a A) '' D) = D :=
    Set.preimage_image_eq D (planeAffine a A).injective
  calc
    _ = Measure.map (planeAffine a A)
        (volume.restrict ((planeAffine a A) ⁻¹' ((planeAffine a A) '' D))) := by rw [hpre]
    _ = _ := by rw [← (planeAffine a A).restrict_map, hm, Measure.restrict_smul]

/-- The transpose (real adjoint) is the frequency map for affine pullback. -/
def affineFrequency (A : (Euclidean d) ≃L[ℝ] (Euclidean d)) : (Euclidean d) →L[ℝ] (Euclidean d) :=
  ContinuousLinearMap.adjoint A.toContinuousLinearMap

theorem affineFrequency_inner (A : (Euclidean d) ≃L[ℝ] (Euclidean d)) (ξ x : (Euclidean d)) :
    inner (𝕜 := ℝ) (affineFrequency A ξ) x = inner (𝕜 := ℝ) ξ (A x) :=
  ContinuousLinearMap.adjoint_inner_left A.toContinuousLinearMap x ξ

theorem affineFrequency_injective (A : (Euclidean d) ≃L[ℝ] (Euclidean d)) :
    Function.Injective (affineFrequency A) := by
  intro ξ η h
  apply ext_inner_right ℝ
  intro x
  obtain ⟨y, rfl⟩ := A.surjective x
  rw [← affineFrequency_inner, ← affineFrequency_inner, h]

theorem exponential_planeAffine (a ξ x : (Euclidean d)) (A : (Euclidean d) ≃L[ℝ] (Euclidean d)) :
    exponential ξ (planeAffine a A x) = exponential ξ a * exponential (affineFrequency A ξ) x := by
  unfold exponential
  change Complex.exp (2 * (Real.pi : ℂ) * Complex.I * (inner (𝕜 := ℝ) ξ (a + A x) : ℂ)) = _
  rw [inner_add_right, Complex.ofReal_add, mul_add, Complex.exp_add, affineFrequency_inner]

theorem exponential_norm (ξ x : Euclidean d) : ‖exponential ξ x‖ = 1 := by
  simp [exponential, Complex.norm_exp, Complex.mul_re]

/--  BAFFINE-01: Pullback by an invertible affine map preserves actual exponential Riesz bases,
with the precise transpose image of the frequency set. -/
theorem hasExponentialRieszBasis_affine_pullback (a : (Euclidean d)) (A : (Euclidean d) ≃L[ℝ] (Euclidean d))
    (D Λ : Set (Euclidean d)) (hΛ : HasExponentialRieszBasis ((planeAffine a A) '' D) Λ) :
    HasExponentialRieszBasis D ((affineFrequency A) '' Λ) := by
  classical
  obtain ⟨S, hS⟩ := hΛ
  let e := Equiv.Set.image (affineFrequency A) Λ (affineFrequency_injective A)
  let w : Λ → ℂ := fun ξ => (exponential ξ.val a)⁻¹
  have hw : ∀ ξ, ‖w ξ‖ = 1 := by intro ξ; simp [w, exponential_norm]
  let U := weightedReindex e w hw
  let B := scaledL2Equiv (planeAffine a A) (planeAffine_map a A D)
    (affineJacobian_ne_zero A) (affineJacobian_ne_top A)
  have hq : QuasiMeasurePreserving (planeAffine a A)
      (volume.restrict D) (volume.restrict ((planeAffine a A) '' D)) :=
    ⟨(planeAffine a A).measurable, by rw [planeAffine_map]; exact smul_absolutelyContinuous⟩
  refine ⟨U.toContinuousLinearEquiv.trans (S.trans B), ?_⟩
  intro η
  obtain ⟨ξ, rfl⟩ := e.surjective η
  change (B (S (weightedReindex e w hw (lp.single 2 (e ξ) 1))) : (Euclidean d) → ℂ) =ᵐ[_] _
  rw [weightedReindex_single, map_smul]
  filter_upwards [scaledL2Equiv_ae (planeAffine a A) (planeAffine_map a A D)
      (affineJacobian_ne_zero A) (affineJacobian_ne_top A) (w ξ • S (lp.single 2 ξ 1)),
    hq.ae (Lp.coeFn_smul (w ξ) (S (lp.single 2 ξ 1))), hq.ae (hS ξ)] with x hx hy hz
  change _ = exponential (affineFrequency A ξ.val) x
  rw [hx]
  change (w ξ • S (lp.single 2 ξ 1)) (planeAffine a A x) = _
  rw [hy]
  change w ξ * S (lp.single 2 ξ 1) (planeAffine a A x) = _
  rw [hz]
  change (exponential ξ.val a)⁻¹ * exponential ξ.val (planeAffine a A x) = _
  rw [exponential_planeAffine, ← mul_assoc, inv_mul_cancel₀, one_mul]
  exact Complex.exp_ne_zero _

/-- The affine inverse is again an affine map. -/
theorem planeAffine_inverse (a : (Euclidean d)) (A : (Euclidean d) ≃L[ℝ] (Euclidean d)) :
    planeAffine (-A.symm a) A.symm = (planeAffine a A).symm := by
  apply MeasurableEquiv.ext
  funext x
  change -A.symm a + A.symm x = A.symm (x - a)
  rw [map_sub]
  abel

/-- Existence of an exponential Riesz basis is invariant under every invertible
real affine coordinate change. -/
theorem exists_exponentialRieszBasis_affine_iff (a : (Euclidean d)) (A : (Euclidean d) ≃L[ℝ] (Euclidean d))
    (D : Set (Euclidean d)) :
    (∃ Λ, HasExponentialRieszBasis ((planeAffine a A) '' D) Λ) ↔
      ∃ Λ, HasExponentialRieszBasis D Λ := by
  constructor
  · rintro ⟨Λ, hΛ⟩
    exact ⟨_, hasExponentialRieszBasis_affine_pullback a A D Λ hΛ⟩
  · rintro ⟨Λ, hΛ⟩
    have hD : (planeAffine (-A.symm a) A.symm) '' ((planeAffine a A) '' D) = D := by
      rw [planeAffine_inverse, Set.image_image]
      simp only [Function.comp_def, MeasurableEquiv.symm_apply_apply, Set.image_id']
    have h := hasExponentialRieszBasis_affine_pullback (-A.symm a) A.symm
      ((planeAffine a A) '' D) Λ (hD.symm ▸ hΛ)
    exact ⟨_, h⟩

end RieszEuclidean

/- Source: RieszEuclidean/FourierL2.lean -/
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
noncomputable section
open MeasureTheory
open scoped FourierTransform
namespace RieszEuclidean

/-- Fourier transposition on integrable Euclidean functions, before conjugation. -/
theorem integral_fourier_mul {d : ℕ} {f g : Euclidean d → ℂ}
    (hf : Integrable f) (hg : Integrable g) :
    (∫ x, 𝓕 f x * g x) = ∫ x, f x * 𝓕 g x := by
  have h := VectorFourier.integral_fourierIntegral_smul_eq_flip
    (L := innerₗ (Euclidean d)) Real.continuous_fourierChar
    (continuous_fst.inner continuous_snd) hf hg
  simpa only [Real.fourierIntegral, smul_eq_mul, flip_innerₗ] using h

/-- Conjugation exchanges the two Fourier signs. -/
theorem fourier_conj_eq_conj_inverse {d : ℕ} (f : Euclidean d → ℂ)
    (x : Euclidean d) :
    𝓕 (fun y => starRingEnd ℂ (f y)) x = starRingEnd ℂ (𝓕⁻ f x) := by
  rw [Real.fourierIntegral_eq, Real.fourierIntegralInv_eq, ← integral_conj]
  congr 1
  ext y
  simp [Circle.smul_def, map_mul]

/-- The Fourier pairing with conjugation uses the inverse transform on the right. -/
theorem integral_fourier_mul_conj {d : ℕ} {f g : Euclidean d → ℂ}
    (hf : Integrable f) (hg : Integrable g) :
    (∫ x, 𝓕 f x * starRingEnd ℂ (g x)) =
      ∫ x, f x * starRingEnd ℂ (𝓕⁻ g x) := by
  have hg' : Integrable (fun x => starRingEnd ℂ (g x)) :=
    Complex.conjCLE.toContinuousLinearMap.integrable_comp hg
  simpa only [fourier_conj_eq_conj_inverse] using integral_fourier_mul hf hg'

/-- Parseval pairing for Euclidean Schwartz functions with the exact Fourier normalization. -/
theorem schwartz_parseval {d : ℕ} (f g : SchwartzMap (Euclidean d) ℂ) :
    (∫ x, 𝓕 f x * starRingEnd ℂ (𝓕 g x)) =
      ∫ x, f x * starRingEnd ℂ (g x) := by
  have h := integral_fourier_mul_conj f.integrable
    (SchwartzMap.fourierTransformCLM ℂ g).integrable
  simpa only [SchwartzMap.fourierTransformCLM_apply,
    Continuous.fourier_inversion g.continuous g.integrable
      (SchwartzMap.fourierTransformCLM ℂ g).integrable] using h


/-- The Schwartz embedding into L² realizes the integral pairing. -/
theorem schwartz_toL2_inner {d : ℕ} (f g : SchwartzMap (Euclidean d) ℂ) :
    inner (𝕜 := ℂ) (f.toLp 2) (g.toLp 2) =
      ∫ x, g x * starRingEnd ℂ (f x) := by
  rw [L2.inner_def]
  apply integral_congr_ae
  filter_upwards [f.coeFn_toLp 2, g.coeFn_toLp 2] with x hf hg
  simp [hf, hg, RCLike.inner_apply, mul_comm]

/-- Fourier preserves the L² inner product of Schwartz functions. -/
theorem schwartz_fourier_inner {d : ℕ} (f g : SchwartzMap (Euclidean d) ℂ) :
    inner (𝕜 := ℂ) ((SchwartzMap.fourierTransformCLM ℂ f).toLp 2)
      ((SchwartzMap.fourierTransformCLM ℂ g).toLp 2) =
      inner (𝕜 := ℂ) (f.toLp 2) (g.toLp 2) := by
  simpa only [schwartz_toL2_inner, SchwartzMap.fourierTransformCLM_apply] using
    schwartz_parseval g f

/-- Parseval in the norm used for the Hilbert-space extension. -/
theorem schwartz_fourier_norm {d : ℕ} (f : SchwartzMap (Euclidean d) ℂ) :
    ‖(SchwartzMap.fourierTransformCLM ℂ f).toLp 2‖ = ‖f.toLp 2‖ := by
  have h := congrArg Complex.re (schwartz_fourier_inner f f)
  change RCLike.re (inner (𝕜 := ℂ) _ _) = RCLike.re (inner (𝕜 := ℂ) _ _) at h
  rw [← norm_sq_eq_re_inner, ← norm_sq_eq_re_inner] at h
  nlinarith [norm_nonneg ((SchwartzMap.fourierTransformCLM ℂ f).toLp 2),
    norm_nonneg (f.toLp 2)]

end RieszEuclidean

/- Source: RieszEuclidean/SchwartzDensity.lean -/
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
noncomputable section
open scoped ContDiff
open Metric Set Function MeasureTheory
open scoped ENNReal
namespace RieszEuclidean

/-- Smooth compactly supported functions are Schwartz functions. -/
def compactSchwartz {d : ℕ} (f : Euclidean d → ℂ)
    (hf : ContDiff ℝ ∞ f) (hs : HasCompactSupport f) :
    SchwartzMap (Euclidean d) ℂ where
  toFun := f
  smooth' := hf
  decay' k n := by
    have hc : Continuous (fun x => ‖x‖ ^ k * ‖iteratedFDeriv ℝ n f x‖) :=
      (continuous_norm.pow k).mul (hf.continuous_iteratedFDeriv (by exact_mod_cast le_top)).norm
    have hcs : HasCompactSupport (fun x => ‖x‖ ^ k * ‖iteratedFDeriv ℝ n f x‖) :=
      (hs.iteratedFDeriv n).norm.mul_left
    obtain ⟨C, hC⟩ := hcs.exists_bound_of_continuous hc
    exact ⟨C, fun x => (le_abs_self _).trans (hC x)⟩


/-- Local mollifier estimates preserve compact support within a fixed thickening. -/
theorem local_approx_support {d : ℕ} {f g : Euclidean d → ℂ} {r : ℝ}
    (hr1 : r ≤ 1)
    (hg : ∀ a δ, (∀ x ∈ ball a r, dist (f x) (f a) ≤ δ) → dist (g a) (f a) ≤ δ) :
    support g ⊆ cthickening 1 (tsupport f) := by
  intro a ha
  by_contra hnot
  have hfzero (x : Euclidean d) (hx : dist a x ≤ 1) : f x = 0 := by
    by_contra hxne
    exact hnot (mem_cthickening_of_dist_le a x 1 (tsupport f)
      (subset_tsupport f hxne) hx)
  have hfa : f a = 0 := hfzero a (by simp)
  have hga := hg a 0 (fun x hx => by
    have hfx := hfzero x ((by simpa [dist_comm] using hx : dist a x < r).le.trans hr1)
    simp [hfx, hfa])
  have : g a = 0 := by simpa [hfa] using hga
  exact ha this

/-- Uniform smooth approximation with all supports in one compact neighbourhood. -/
theorem smooth_compact_uniform_approx {d : ℕ} {f : Euclidean d → ℂ}
    (hf : Continuous f) (hs : HasCompactSupport f) {ε : ℝ} (hε : 0 < ε) :
    ∃ g : Euclidean d → ℂ, ContDiff ℝ ∞ g ∧ HasCompactSupport g ∧
      support g ⊆ cthickening 1 (tsupport f) ∧ ∀ x, dist (g x) (f x) < ε := by
  obtain ⟨δ, hδ, hu⟩ := Metric.uniformContinuous_iff.mp
    (hs.uniformContinuous_of_continuous hf) (ε / 2) (half_pos hε)
  obtain ⟨g, hg, hbound⟩ :=
    hf.exists_contDiff_dist_le_of_forall_mem_ball_dist_le (lt_min one_pos hδ)
  have hsupp := local_approx_support (min_le_left 1 δ) hbound
  refine ⟨g, hg, HasCompactSupport.of_support_subset_isCompact
    hs.cthickening hsupp, hsupp, fun x => ?_⟩
  apply (hbound x (ε / 2) ?_).trans_lt (half_lt_self hε)
  intro y hy
  apply (hu ?_).le
  exact (mem_ball.mp hy).trans_le (min_le_right 1 δ)


/-- A uniform bound on a finite support gives the usual L² estimate. -/
theorem eLpNorm_two_le_of_support {d : ℕ} {f : Euclidean d → ℂ}
    {K : Set (Euclidean d)} (hK : MeasurableSet K) (hs : support f ⊆ K)
    {C : ℝ} (hC : ∀ x, ‖f x‖ ≤ C) :
    eLpNorm f 2 volume ≤ volume K ^ (1 / (2 : ℝ)) * ENNReal.ofReal C := by
  have heq : K.indicator f = f := indicator_eq_self.mpr hs
  rw [← heq, eLpNorm_indicator_eq_eLpNorm_restrict hK]
  simpa using (eLpNorm_le_of_ae_bound (p := 2) (μ := volume.restrict K)
    (Filter.Eventually.of_forall hC))
/-- Continuous compactly supported functions admit Schwartz approximation in L². -/
theorem compact_exists_schwartz_eLpNorm_lt {d : ℕ} {f : Euclidean d → ℂ}
    (hf : Continuous f) (hs : HasCompactSupport f) {ε : ℝ≥0∞} (hε : ε ≠ 0) :
    ∃ g : SchwartzMap (Euclidean d) ℂ, eLpNorm (f - (g : Euclidean d → ℂ)) 2 volume < ε := by
  let K := Metric.cthickening 1 (tsupport f)
  have hK : IsCompact K := hs.cthickening
  have hfinite : volume K ^ (1 / (2 : ℝ)) ≠ ⊤ :=
    ENNReal.rpow_ne_top_of_nonneg (by positivity) hK.measure_lt_top.ne
  obtain ⟨η, hη, hηε⟩ := ENNReal.exists_nnreal_pos_mul_lt hfinite hε
  obtain ⟨g, hg, hgs, hsupport, happrox⟩ :=
    smooth_compact_uniform_approx hf hs (show 0 < (η : ℝ) from hη)
  refine ⟨compactSchwartz g hg hgs, ?_⟩
  have hfs : support f ⊆ K :=
    (subset_tsupport f).trans (Metric.self_subset_cthickening (tsupport f))
  have hdiff : support (f - g) ⊆ K :=
    (support_sub f g).trans (union_subset hfs hsupport)
  have hb := eLpNorm_two_le_of_support hK.measurableSet hdiff
    (C := (η : ℝ)) (fun x => by
      simpa only [Pi.sub_apply, ← dist_eq_norm, dist_comm] using (happrox x).le)
  exact hb.trans_lt (by simpa only [ENNReal.ofReal_coe_nnreal, mul_comm] using hηε)

/-- Schwartz functions approximate every Euclidean L² function in the L² seminorm. -/
theorem memLp_exists_schwartz_eLpNorm_lt {d : ℕ} {f : Euclidean d → ℂ}
    (hf : MemLp f 2 volume) {ε : ℝ≥0∞} (hε : ε ≠ 0) :
    ∃ g : SchwartzMap (Euclidean d) ℂ,
      eLpNorm (f - (g : Euclidean d → ℂ)) 2 volume < ε := by
  obtain ⟨η, hη, hηε⟩ := ENNReal.exists_nnreal_pos_mul_lt (a := 2) (by norm_num) hε
  have hη0 : (η : ℝ≥0∞) ≠ 0 := by exact_mod_cast hη.ne'
  obtain ⟨c, hcs, hfc, hc, hcm⟩ :=
    hf.exists_hasCompactSupport_eLpNorm_sub_le (by norm_num) hη0
  obtain ⟨g, hcg⟩ := compact_exists_schwartz_eLpNorm_lt hc hcs hη0
  refine ⟨g, ?_⟩
  have hsum := eLpNorm_add_le (hf.aestronglyMeasurable.sub hcm.aestronglyMeasurable)
    (hcm.aestronglyMeasurable.sub g.continuous.aestronglyMeasurable) (by norm_num : (1 : ℝ≥0∞) ≤ 2)
  have heq : (f - c) + (c - (g : Euclidean d → ℂ)) = f - (g : Euclidean d → ℂ) := by abel
  rw [heq] at hsum
  calc
    eLpNorm (f - (g : Euclidean d → ℂ)) 2 volume
        ≤ eLpNorm (f - c) 2 volume + eLpNorm (c - (g : Euclidean d → ℂ)) 2 volume := hsum
    _ ≤ (η : ℝ≥0∞) + η := add_le_add hfc hcg.le
    _ < ε := by simpa only [mul_two] using hηε

/-- The Schwartz embedding has dense range in the actual Euclidean L² space. -/
theorem schwartz_toL2_denseRange (d : ℕ) :
    DenseRange (fun g : SchwartzMap (Euclidean d) ℂ => g.toLp 2 volume) := by
  rw [Metric.denseRange_iff]
  intro f ε hε
  obtain ⟨g, hg⟩ := memLp_exists_schwartz_eLpNorm_lt (Lp.memLp f)
    (show ENNReal.ofReal ε ≠ 0 by positivity)
  refine ⟨g, ?_⟩
  rw [Lp.dist_def]
  have heq : eLpNorm ((f : Euclidean d → ℂ) - (g.toLp 2 volume : Euclidean d → ℂ)) 2 volume =
      eLpNorm ((f : Euclidean d → ℂ) - (g : Euclidean d → ℂ)) 2 volume := by
    apply eLpNorm_congr_ae
    filter_upwards [g.coeFn_toLp 2 volume] with x hx
    simp only [Pi.sub_apply, hx]
  rw [heq]
  exact ENNReal.toReal_lt_of_lt_ofReal hg

end RieszEuclidean

/- Source: RieszEuclidean/FourierExtension.lean -/
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
noncomputable section
open MeasureTheory
namespace RieszEuclidean
/-- Ambient Euclidean L² space. -/
abbrev FullL2 (d : ℕ) := Lp ℂ 2 (volume : Measure (Euclidean d))
/-- The Schwartz subspace with its inherited L² norm. -/
def schwartzL2 (d : ℕ) : Submodule ℂ (FullL2 d) :=
  LinearMap.range (SchwartzMap.toLpCLM ℂ ℂ 2 (volume : Measure (Euclidean d))).toLinearMap
/-- Identify Schwartz functions with their actual L² representatives. -/
def schwartzL2Equiv (d : ℕ) : SchwartzMap (Euclidean d) ℂ ≃ₗ[ℂ] schwartzL2 d :=
  LinearEquiv.ofInjective (SchwartzMap.toLpCLM ℂ ℂ 2 volume).toLinearMap
    (SchwartzMap.injective_toLp 2 volume)
/-- Fourier transform restricted to the dense Schwartz subspace. -/
def schwartzFourierIsometry (d : ℕ) : schwartzL2 d ≃ₗᵢ[ℂ] schwartzL2 d where
  toLinearEquiv := (schwartzL2Equiv d).symm.trans
    ((SchwartzMap.fourierTransformCLE ℂ).toLinearEquiv.trans (schwartzL2Equiv d))
  norm_map' x := by
    obtain ⟨f, rfl⟩ := (schwartzL2Equiv d).surjective x
    simpa [schwartzL2Equiv] using schwartz_fourier_norm f
/-- The inclusion of the Schwartz subspace into L² has dense range. -/
theorem schwartzL2_dense (d : ℕ) : DenseRange (schwartzL2 d).subtypeL := by
  rw [Metric.denseRange_iff]
  intro x ε hε
  obtain ⟨f, hf⟩ := Metric.denseRange_iff.mp (schwartz_toL2_denseRange d) x ε hε
  exact ⟨schwartzL2Equiv d f, hf⟩
/-- Continuous extension of the negative-sign Fourier transform to Euclidean L². -/
def fourierL2CLM (d : ℕ) : FullL2 d →L[ℂ] FullL2 d :=
  ((schwartzL2 d).subtypeL.comp
    (schwartzFourierIsometry d).toContinuousLinearEquiv.toContinuousLinearMap).extend
    (schwartzL2 d).subtypeL (schwartzL2_dense d)
    (schwartzL2 d).subtypeₗᵢ.isometry.isUniformInducing
/-- The extension agrees with Fourier on the Schwartz subspace. -/
theorem fourierL2CLM_subtype (d : ℕ) (x : schwartzL2 d) :
    fourierL2CLM d x = (schwartzFourierIsometry d x : FullL2 d) :=
  ContinuousLinearMap.extend_eq _ _ _ _ x
/-- The extended Fourier transform preserves the L² norm. -/
theorem fourierL2CLM_norm (d : ℕ) (x : FullL2 d) : ‖fourierL2CLM d x‖ = ‖x‖ := by
  refine (schwartzL2_dense d).induction_on (p := fun y => ‖fourierL2CLM d y‖ = ‖y‖) x ?_ ?_
  · exact isClosed_eq ((fourierL2CLM d).continuous.norm) continuous_norm
  · intro y
    change ‖fourierL2CLM d (y : FullL2 d)‖ = ‖(y : FullL2 d)‖
    rw [fourierL2CLM_subtype]
    exact (schwartzFourierIsometry d).norm_map y
/-- The extended transform as a linear isometry. -/
def fourierL2Isometry (d : ℕ) : FullL2 d →ₗᵢ[ℂ] FullL2 d where
  toLinearMap := (fourierL2CLM d).toLinearMap
  norm_map' := fourierL2CLM_norm d
/-- The extended transform has dense range, by Schwartz inversion. -/
theorem fourierL2_dense (d : ℕ) : DenseRange (fourierL2Isometry d) := by
  rw [Metric.denseRange_iff]
  intro x ε hε
  obtain ⟨y, hy⟩ := Metric.denseRange_iff.mp (schwartzL2_dense d) x ε hε
  refine ⟨((schwartzFourierIsometry d).symm y : FullL2 d), ?_⟩
  change dist x (fourierL2CLM d _) < ε
  rw [fourierL2CLM_subtype, LinearIsometryEquiv.apply_symm_apply]
  exact hy
/-- Completeness closes the isometric range, so the Fourier extension is onto. -/
theorem fourierL2_surjective (d : ℕ) : Function.Surjective (fourierL2Isometry d) := by
  apply Set.range_eq_univ.mp
  rw [← (fourierL2Isometry d).isometry.isClosedEmbedding.isClosed_range.closure_eq]
  exact (fourierL2_dense d).closure_eq
/-- Unitary negative-sign Euclidean Fourier transform on L². -/
def fourierL2Equiv (d : ℕ) : FullL2 d ≃ₗᵢ[ℂ] FullL2 d :=
  LinearIsometryEquiv.ofSurjective (fourierL2Isometry d) (fourierL2_surjective d)
/-- The unitary extension has the exact Schwartz Fourier values. -/
theorem fourierL2Equiv_schwartz (d : ℕ) (f : SchwartzMap (Euclidean d) ℂ) :
    fourierL2Equiv d (f.toLp 2 volume) =
      (SchwartzMap.fourierTransformCLE ℂ f).toLp 2 volume := by
  change fourierL2CLM d (f.toLp 2 volume) = _
  have h := fourierL2CLM_subtype d (schwartzL2Equiv d f)
  simpa [schwartzFourierIsometry, schwartzL2Equiv] using h
/-- The inverse extension agrees with inverse Fourier on Schwartz functions. -/
theorem fourierL2Equiv_symm_schwartz (d : ℕ) (f : SchwartzMap (Euclidean d) ℂ) :
    (fourierL2Equiv d).symm (f.toLp 2 volume) =
      ((SchwartzMap.fourierTransformCLE ℂ).symm f).toLp 2 volume := by
  apply (fourierL2Equiv d).injective
  rw [LinearIsometryEquiv.apply_symm_apply, fourierL2Equiv_schwartz,
    ContinuousLinearEquiv.apply_symm_apply]
/-- The paper's positive-sign Fourier transform, defined on all of Euclidean L². -/
def paperFourierL2 (d : ℕ) : FullL2 d ≃ₗᵢ[ℂ] FullL2 d := (fourierL2Equiv d).symm
/-- Exact positive-sign integral formula on the dense Schwartz subspace. -/
theorem paperFourierL2_schwartz (d : ℕ) (f : SchwartzMap (Euclidean d) ℂ) :
    (paperFourierL2 d (f.toLp 2 volume) : Euclidean d → ℂ) =ᵐ[volume]
      Real.fourierIntegralInv f := by
  rw [paperFourierL2, fourierL2Equiv_symm_schwartz]
  exact (((SchwartzMap.fourierTransformCLE ℂ).symm f).coeFn_toLp 2 volume).trans
    (Filter.Eventually.of_forall (fun x => congrFun
      (SchwartzMap.fourierTransformCLE_symm_apply ℂ f) x))
end RieszEuclidean

/- Source: RieszEuclidean/ProjectionGap.lean -/
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
/-! Blueprint: blueprint/README.md#projection-gap. -/
noncomputable section
namespace RieszEuclidean

variable (H : Type) [NormedAddCommGroup H] [InnerProductSpace ℂ H]

/-- A bounded orthogonal projection; closed range follows from idempotence. -/
structure OrthProjection where
  /-- The bounded complex linear operator underlying the projection. -/
  op : H →L[ℂ] H
  idempotent : op.comp op = op
  symmetric : ∀ x y : H, inner (𝕜 := ℂ) (op x) y = inner (𝕜 := ℂ) x (op y)

namespace OrthProjection
variable {H}

/-- The range submodule of the projection. -/
def range (P : OrthProjection H) : Submodule ℂ H := LinearMap.range P.op

/-- The restriction of P to the range of Q is a continuous linear equivalence. -/
def RangeIso (P Q : OrthProjection H) : Prop :=
  ∃ e : Q.range ≃L[ℂ] P.range, ∀ x : Q.range, (e x : H) = P.op x

/-- Pointwise norm convergence of a sequence of bounded operators. -/
def StronglyConverges (P : ℕ → H →L[ℂ] H) (R : H →L[ℂ] H) : Prop :=
  ∀ x, Filter.Tendsto (fun n => P n x) Filter.atTop (nhds (R x))

theorem apply_idempotent (P : OrthProjection H) (x : H) : P.op (P.op x) = P.op x :=
  DFunLike.congr_fun P.idempotent x

/-- Transport a projection through a linear isometry onto its ambient space. -/
def conjugate {K : Type} [NormedAddCommGroup K] [InnerProductSpace ℂ K]
    (P : OrthProjection H) (e : K ≃ₗᵢ[ℂ] H) : OrthProjection K where
  op := e.symm.toContinuousLinearEquiv.toContinuousLinearMap.comp
    (P.op.comp e.toContinuousLinearEquiv.toContinuousLinearMap)
  idempotent := by
    ext x
    change e.symm (P.op (e (e.symm (P.op (e x))))) = e.symm (P.op (e x))
    rw [e.apply_symm_apply, P.apply_idempotent]
  symmetric := by
    intro x y
    rw [← e.inner_map_map, ← e.inner_map_map]
    change inner (𝕜 := ℂ) (e (e.symm (P.op (e x)))) (e y) =
      inner (𝕜 := ℂ) (e x) (e (e.symm (P.op (e y))))
    simp only [e.apply_symm_apply]
    exact P.symmetric (e x) (e y)

theorem mem_range_iff (P : OrthProjection H) (x : H) : x ∈ P.range ↔ P.op x = x := by
  constructor
  · rintro ⟨y, rfl⟩
    exact P.apply_idempotent y
  · intro hx
    exact ⟨x, hx⟩

theorem inner_op_sub_op (P : OrthProjection H) (x y : H) :
    inner (𝕜 := ℂ) (P.op x) (y - P.op y) = 0 := by
  rw [P.symmetric, map_sub, P.apply_idempotent, _root_.sub_self, inner_zero_right]

theorem norm_sq_decomposition (P : OrthProjection H) (x : H) :
    ‖P.op x‖ ^ 2 + ‖x - P.op x‖ ^ 2 = ‖x‖ ^ 2 := by
  have h := norm_add_sq_eq_norm_sq_add_norm_sq_of_inner_eq_zero
    (P.op x) (x - P.op x) (P.inner_op_sub_op x x)
  simpa only [add_sub_cancel, pow_two] using h.symm

theorem norm_op_apply_le (P : OrthProjection H) (x : H) : ‖P.op x‖ ≤ ‖x‖ := by
  have h := P.norm_sq_decomposition x
  nlinarith [sq_nonneg ‖x - P.op x‖, norm_nonneg (P.op x), norm_nonneg x]

theorem norm_sub_op_apply_le (P : OrthProjection H) (x : H) : ‖x - P.op x‖ ≤ ‖x‖ := by
  have h := P.norm_sq_decomposition x
  nlinarith [sq_nonneg ‖P.op x‖, norm_nonneg (x - P.op x), norm_nonneg x]

theorem norm_sub_apply_sq (P Q : OrthProjection H) (x : H) :
    ‖(P.op - Q.op) x‖ ^ 2 =
      ‖P.op (x - Q.op x)‖ ^ 2 + ‖Q.op x - P.op (Q.op x)‖ ^ 2 := by
  have h := norm_sub_sq (𝕜 := ℂ) (P.op (x - Q.op x)) (Q.op x - P.op (Q.op x))
  rw [P.inner_op_sub_op, map_zero, mul_zero, sub_zero] at h
  simpa only [ContinuousLinearMap.sub_apply, map_sub, sub_sub_sub_cancel_right] using h

instance range_completeSpace [CompleteSpace H] (P : OrthProjection H) :
    CompleteSpace P.range := by
  have h : IsClosed (P.range : Set H) := by
    have heq : (P.range : Set H) = {x | P.op x = x} := by
      ext x
      exact P.mem_range_iff x
    rw [heq]
    exact isClosed_eq P.op.continuous continuous_id
  exact h.completeSpace_coe

/-- The actual restriction of one projection to the range of another. -/
def between (P Q : OrthProjection H) : Q.range →L[ℂ] P.range :=
  (P.op.comp Q.range.subtypeL).codRestrict P.range (fun x => ⟨x, rfl⟩)

theorem rangeIso_of_gap [CompleteSpace H] (P Q : OrthProjection H)
    (hgap : ‖P.op - Q.op‖ < 1) : RangeIso P Q := by
  let A := P.between Q
  let B := Q.between P
  have hnorm : ‖1 - A.comp B‖ ≤ ‖P.op - Q.op‖ := by
    apply ContinuousLinearMap.opNorm_le_bound _ (norm_nonneg _)
    intro x
    have hx : P.op x = x := (P.mem_range_iff x).mp x.property
    change ‖(x : H) - P.op (Q.op x)‖ ≤ ‖P.op - Q.op‖ * ‖(x : H)‖
    calc
      ‖(x : H) - P.op (Q.op x)‖ = ‖P.op ((P.op - Q.op) x)‖ := by
        simp only [ContinuousLinearMap.sub_apply, map_sub, P.apply_idempotent, hx]
      _ ≤ ‖(P.op - Q.op) x‖ := P.norm_op_apply_le _
      _ ≤ ‖P.op - Q.op‖ * ‖(x : H)‖ := (P.op - Q.op).le_opNorm x
  have hunit : IsUnit (A.comp B) := by
    simpa only [sub_sub_cancel] using
      isUnit_one_sub_of_norm_lt_one (x := 1 - A.comp B) (hnorm.trans_lt hgap)
  have hsurj : Function.Surjective A := by
    have hAB := (ContinuousLinearMap.isUnit_iff_bijective.mp hunit).surjective
    intro y
    obtain ⟨x, hx⟩ := hAB y
    exact ⟨B x, hx⟩
  have hinj : Function.Injective A := by
    apply (injective_iff_map_eq_zero A).mpr
    intro x hx
    have hPx : P.op x = 0 := congrArg Subtype.val hx
    have hQx : Q.op x = x := (Q.mem_range_iff x).mp x.property
    have hbound := (P.op - Q.op).le_opNorm (x : H)
    simp only [ContinuousLinearMap.sub_apply, hPx, hQx, _root_.zero_sub, norm_neg] at hbound
    have hxzero : ‖(x : H)‖ = 0 := by
      nlinarith [norm_nonneg (x : H)]
    exact Subtype.ext (norm_eq_zero.mp hxzero)
  exact ⟨ContinuousLinearEquiv.ofBijective A
    (LinearMap.ker_eq_bot.mpr hinj) (LinearMap.range_eq_top.mpr hsurj), fun _ => rfl⟩

theorem lower_bounds_of_rangeIso (P Q : OrthProjection H) (h : RangeIso P Q) :
    ∃ c : ℝ, 0 < c ∧ c ≤ 1 ∧
      (∀ x ∈ Q.range, c * ‖x‖ ≤ ‖P.op x‖) ∧
      (∀ y ∈ P.range, c * ‖y‖ ≤ ‖Q.op y‖) := by
  obtain ⟨e, he⟩ := h
  let K := ‖e.symm.toContinuousLinearMap‖ + 1
  have hK : 0 < K := by dsimp [K]; positivity
  have hKnorm : ‖e.symm.toContinuousLinearMap‖ ≤ K := by dsimp [K]; linarith
  have hxbound (x : Q.range) : ‖(x : H)‖ ≤ K * ‖P.op x‖ := by
    have hnorm := e.symm.toContinuousLinearMap.le_opNorm (e x)
    have heq : ‖e x‖ = ‖P.op x‖ := congrArg norm (he x)
    simp only [ContinuousLinearEquiv.coe_coe, e.symm_apply_apply, heq] at hnorm
    exact hnorm.trans (mul_le_mul_of_nonneg_right hKnorm (norm_nonneg _))
  have hybound (y : P.range) : ‖(y : H)‖ ≤ K * ‖Q.op y‖ := by
    let x := e.symm y
    have hPx : P.op x = y := by rw [← he, e.apply_symm_apply]
    have hQx : Q.op x = x := (Q.mem_range_iff x).mp x.property
    have hPy : P.op y = y := (P.mem_range_iff y).mp y.property
    have hinner : inner (𝕜 := ℂ) (x : H) (Q.op y) = inner (𝕜 := ℂ) (y : H) y := by
      calc
        inner (𝕜 := ℂ) (x : H) (Q.op y) = inner (𝕜 := ℂ) (Q.op x) (y : H) :=
          (Q.symmetric x y).symm
        _ = inner (𝕜 := ℂ) (x : H) (y : H) := by rw [hQx]
        _ = inner (𝕜 := ℂ) (x : H) (P.op y) := by rw [hPy]
        _ = inner (𝕜 := ℂ) (P.op x) (y : H) := (P.symmetric x y).symm
        _ = inner (𝕜 := ℂ) (y : H) y := by rw [hPx]
    have hCS := re_inner_le_norm (𝕜 := ℂ) (x : H) (Q.op y)
    rw [hinner, inner_self_eq_norm_sq] at hCS
    have hx := hxbound x
    rw [hPx] at hx
    have hprod := hCS.trans (mul_le_mul_of_nonneg_right hx (norm_nonneg (Q.op y)))
    by_cases hy : ‖(y : H)‖ = 0
    · rw [hy]
      exact mul_nonneg hK.le (norm_nonneg _)
    · have hypos : 0 < ‖(y : H)‖ := lt_of_le_of_ne (norm_nonneg _) (Ne.symm hy)
      apply (mul_le_mul_left hypos).mp
      nlinarith only [hprod]
  refine ⟨1 / K, div_pos zero_lt_one hK, ?_, ?_, ?_⟩
  · apply (div_le_one hK).mpr
    dsimp [K]
    linarith [norm_nonneg e.symm.toContinuousLinearMap]
  · intro x hx
    have hbound := hxbound ⟨x, hx⟩
    calc
      1 / K * ‖x‖ = ‖x‖ / K := by ring
      _ ≤ ‖P.op x‖ := (div_le_iff₀ hK).mpr (by simpa only [mul_comm] using hbound)
  · intro y hy
    have hbound := hybound ⟨y, hy⟩
    calc
      1 / K * ‖y‖ = ‖y‖ / K := by ring
      _ ≤ ‖Q.op y‖ := (div_le_iff₀ hK).mpr (by simpa only [mul_comm] using hbound)

theorem complement_bound_of_lower (P Q : OrthProjection H) {c b : ℝ}
    (hc : 0 ≤ c) (hb : 0 ≤ b) (hcb : b ^ 2 = 1 - c ^ 2)
    (hlower : ∀ x ∈ Q.range, c * ‖x‖ ≤ ‖P.op x‖) (x : H) (hx : x ∈ Q.range) :
    ‖x - P.op x‖ ≤ b * ‖x‖ := by
  have hlowersq := pow_le_pow_left₀ (mul_nonneg hc (norm_nonneg x)) (hlower x hx) 2
  have hsq : ‖x - P.op x‖ ^ 2 ≤ (b * ‖x‖) ^ 2 := by
    calc
      ‖x - P.op x‖ ^ 2 = ‖x‖ ^ 2 - ‖P.op x‖ ^ 2 := by
        linarith [P.norm_sq_decomposition x]
      _ ≤ ‖x‖ ^ 2 - (c * ‖x‖) ^ 2 := sub_le_sub_left hlowersq _
      _ = (b * ‖x‖) ^ 2 := by rw [mul_pow, mul_pow, hcb]; ring
  nlinarith [mul_nonneg hb (norm_nonneg x), norm_nonneg (x - P.op x)]

theorem bound_on_kernel_of_complement_bound (P Q : OrthProjection H) {b : ℝ}
    (hb : 0 ≤ b) (hbound : ∀ y ∈ P.range, ‖y - Q.op y‖ ≤ b * ‖y‖)
    (z : H) (hz : Q.op z = 0) : ‖P.op z‖ ≤ b * ‖z‖ := by
  have hinner : inner (𝕜 := ℂ) (P.op z - Q.op (P.op z)) z =
      inner (𝕜 := ℂ) (P.op z) (P.op z) := by
    rw [inner_sub_left, Q.symmetric, hz, inner_zero_right, sub_zero]
    exact sub_eq_zero.mp (by simpa only [inner_sub_right] using P.inner_op_sub_op z z)
  have hCS := re_inner_le_norm (𝕜 := ℂ) (P.op z - Q.op (P.op z)) z
  rw [hinner, inner_self_eq_norm_sq] at hCS
  have hprod := hCS.trans (mul_le_mul_of_nonneg_right
    (hbound (P.op z) ⟨z, rfl⟩) (norm_nonneg z))
  by_cases hp : ‖P.op z‖ = 0
  · rw [hp]
    exact mul_nonneg hb (norm_nonneg z)
  · have hpos : 0 < ‖P.op z‖ := lt_of_le_of_ne (norm_nonneg _) (Ne.symm hp)
    apply (mul_le_mul_left hpos).mp
    nlinarith only [hprod]

theorem gap_of_rangeIso (P Q : OrthProjection H) (h : RangeIso P Q) :
    ‖P.op - Q.op‖ < 1 := by
  obtain ⟨c, hc, hc₁, hP, hQ⟩ := P.lower_bounds_of_rangeIso Q h
  let b := Real.sqrt (1 - c ^ 2)
  have hb : 0 ≤ b := Real.sqrt_nonneg _
  have hb_sq : b ^ 2 = 1 - c ^ 2 := Real.sq_sqrt (by nlinarith)
  have hb₁ : b < 1 := by nlinarith [sq_pos_of_pos hc]
  have hPcomp := P.complement_bound_of_lower Q hc.le hb hb_sq hP
  have hQcomp := Q.complement_bound_of_lower P hc.le hb hb_sq hQ
  apply lt_of_le_of_lt _ hb₁
  apply ContinuousLinearMap.opNorm_le_bound _ hb
  intro x
  have h₁ := P.bound_on_kernel_of_complement_bound Q hb hQcomp (x - Q.op x)
    (by rw [map_sub, Q.apply_idempotent, _root_.sub_self])
  have h₂ := hPcomp (Q.op x) ⟨x, rfl⟩
  have h₁sq := pow_le_pow_left₀ (norm_nonneg _) h₁ 2
  have h₂sq := pow_le_pow_left₀ (norm_nonneg _) h₂ 2
  have hsq : ‖(P.op - Q.op) x‖ ^ 2 ≤ (b * ‖x‖) ^ 2 := by
    calc
      ‖(P.op - Q.op) x‖ ^ 2 =
          ‖P.op (x - Q.op x)‖ ^ 2 + ‖Q.op x - P.op (Q.op x)‖ ^ 2 :=
        P.norm_sub_apply_sq Q x
      _ ≤ (b * ‖x - Q.op x‖) ^ 2 + (b * ‖Q.op x‖) ^ 2 := add_le_add h₁sq h₂sq
      _ = b ^ 2 * (‖Q.op x‖ ^ 2 + ‖x - Q.op x‖ ^ 2) := by ring
      _ = (b * ‖x‖) ^ 2 := by rw [Q.norm_sq_decomposition, mul_pow]
  nlinarith [mul_nonneg hb (norm_nonneg x), norm_nonneg ((P.op - Q.op) x)]

/-- GAP-01: manuscript Lemma 2.1. -/
theorem gap_iff_rangeIso [CompleteSpace H] (P Q : OrthProjection H) :
    ‖P.op - Q.op‖ < 1 ↔ RangeIso P Q := by
  exact ⟨P.rangeIso_of_gap Q, P.gap_of_rangeIso Q⟩

/-- GAP-02: Lemma 2.2; infinite-dimensional nesting, not rank counting. -/
theorem nested_not_both_gap [CompleteSpace H] (Rminus Rplus M : OrthProjection H)
    (hnest : Rminus.range < Rplus.range) :
    ¬ (‖Rminus.op - M.op‖ < 1 ∧ ‖Rplus.op - M.op‖ < 1) := by
  rintro ⟨hminus, hplus⟩
  have hm : ‖M.op - Rminus.op‖ < 1 := by
    rwa [norm_sub_rev]
  have hp : ‖M.op - Rplus.op‖ < 1 := by
    rwa [norm_sub_rev]
  obtain ⟨eminus, heminus⟩ := (gap_iff_rangeIso M Rminus).mp hm
  obtain ⟨eplus, heplus⟩ := (gap_iff_rangeIso M Rplus).mp hp
  obtain ⟨w, hwplus, hwminus⟩ := SetLike.exists_of_lt hnest
  let wplus : Rplus.range := ⟨w, hwplus⟩
  obtain ⟨u, hu⟩ := eminus.surjective (eplus wplus)
  let uplus : Rplus.range := ⟨u, hnest.le u.property⟩
  have heq : eplus uplus = eplus wplus := by
    apply Subtype.ext
    calc
      (eplus uplus : H) = M.op uplus := heplus uplus
      _ = (eminus u : H) := (heminus u).symm
      _ = (eplus wplus : H) := congrArg Subtype.val hu
  have huw : (u : H) = w := congrArg Subtype.val (eplus.injective heq)
  exact hwminus (huw ▸ u.property)

/-- GAP-03: the distance between two orthogonal projections is at most one. -/
theorem distance_le_one (P Q : OrthProjection H) : ‖P.op - Q.op‖ ≤ 1 := by
  apply ContinuousLinearMap.opNorm_le_bound _ zero_le_one
  intro x
  rw [one_mul]
  have h := P.norm_sub_apply_sq Q x
  have h₁ := P.norm_sq_decomposition (x - Q.op x)
  have h₂ := P.norm_sq_decomposition (Q.op x)
  have h₃ := Q.norm_sq_decomposition x
  nlinarith [sq_nonneg ‖x - Q.op x - P.op (x - Q.op x)‖,
    sq_nonneg ‖P.op (Q.op x)‖, norm_nonneg ((P.op - Q.op) x), norm_nonneg x]

/-- GAP-04: a UNIFORM non-strict norm bound survives a strong limit. -/
theorem gap_le_of_strong_limit (P : ℕ → H →L[ℂ] H) (R M : H →L[ℂ] H)
    (γ : ℝ) (hlim : StronglyConverges P R) (hgap : ∀ n, ‖P n - M‖ ≤ γ) :
    ‖R - M‖ ≤ γ := by
  have hγ : 0 ≤ γ := (norm_nonneg (P 0 - M)).trans (hgap 0)
  apply ContinuousLinearMap.opNorm_le_bound (R - M) hγ
  intro x
  have hx := ((hlim x).sub_const (M x)).norm
  change Filter.Tendsto (fun n => ‖(P n - M) x‖) Filter.atTop
    (nhds ‖(R - M) x‖) at hx
  apply le_of_tendsto' hx
  intro n
  exact ((P n - M).le_opNorm x).trans
    (mul_le_mul_of_nonneg_right (hgap n) (norm_nonneg x))

end OrthProjection
end RieszEuclidean

/- Source: RieszEuclidean/CutoffProjection.lean -/
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
noncomputable section
open MeasureTheory Set
namespace RieszEuclidean
/-- Multiplication by the domain indicator on actual L² classes. -/
def domainCutoff {d : ℕ} (Ω : Set (Euclidean d)) (hΩ : MeasurableSet Ω)
    (f : FullL2 d) : FullL2 d := ((Lp.memLp f).indicator hΩ).toLp (Ω.indicator f)
/-- The cutoff has the expected almost-everywhere representative. -/
theorem domainCutoff_coe {d : ℕ} (Ω : Set (Euclidean d)) (hΩ : MeasurableSet Ω)
    (f : FullL2 d) : (domainCutoff Ω hΩ f : Euclidean d → ℂ) =ᵐ[volume] Ω.indicator f :=
  MemLp.coeFn_toLp _
/-- Indicator multiplication contracts the L² norm. -/
theorem domainCutoff_norm_le {d : ℕ} (Ω : Set (Euclidean d)) (hΩ : MeasurableSet Ω)
    (f : FullL2 d) : ‖domainCutoff Ω hΩ f‖ ≤ ‖f‖ := by
  apply Lp.norm_le_norm_of_ae_le
  filter_upwards [domainCutoff_coe Ω hΩ f] with x hx
  rw [hx]
  exact norm_indicator_le_norm_self _ _
/-- The domain cutoff as a complex linear map. -/
def domainCutoffLM {d : ℕ} (Ω : Set (Euclidean d)) (hΩ : MeasurableSet Ω) :
    FullL2 d →ₗ[ℂ] FullL2 d where
  toFun := domainCutoff Ω hΩ
  map_add' f g := by
    apply Lp.ext
    filter_upwards [domainCutoff_coe Ω hΩ (f + g), domainCutoff_coe Ω hΩ f,
      domainCutoff_coe Ω hΩ g, Lp.coeFn_add f g,
      Lp.coeFn_add (domainCutoff Ω hΩ f) (domainCutoff Ω hΩ g)] with x h1 h2 h3 h4 h5
    simp only [h1, h5, Pi.add_apply, h2, h3]
    by_cases hx : x ∈ Ω
    · simpa only [indicator_of_mem hx, Pi.add_apply] using h4
    · simp only [indicator_of_not_mem hx, add_zero]
  map_smul' c f := by
    apply Lp.ext
    filter_upwards [domainCutoff_coe Ω hΩ (c • f), domainCutoff_coe Ω hΩ f,
      Lp.coeFn_smul c f, Lp.coeFn_smul c (domainCutoff Ω hΩ f)] with x h1 h2 h3 h4
    simp only [h1, h4, Pi.smul_apply, h2, RingHom.id_apply]
    by_cases hx : x ∈ Ω <;> simp [hx, h3]
/-- The domain cutoff is a bounded complex linear operator. -/
def domainCutoffCLM {d : ℕ} (Ω : Set (Euclidean d)) (hΩ : MeasurableSet Ω) :
    FullL2 d →L[ℂ] FullL2 d :=
  (domainCutoffLM Ω hΩ).mkContinuous 1 (fun f => by simpa using domainCutoff_norm_le Ω hΩ f)
/-- Multiplication by a measurable indicator is an orthogonal projection. -/
def domainProjection {d : ℕ} (Ω : Set (Euclidean d)) (hΩ : MeasurableSet Ω) :
    OrthProjection (FullL2 d) where
  op := domainCutoffCLM Ω hΩ
  idempotent := by
    ext f
    filter_upwards [domainCutoff_coe Ω hΩ (domainCutoff Ω hΩ f),
      domainCutoff_coe Ω hΩ f] with x h1 h2
    change (domainCutoff Ω hΩ (domainCutoff Ω hΩ f) : Euclidean d → ℂ) x =
      (domainCutoff Ω hΩ f : Euclidean d → ℂ) x
    rw [h1, h2]
    by_cases hx : x ∈ Ω <;> simp [hx, h2]
  symmetric f g := by
    rw [L2.inner_def, L2.inner_def]
    apply integral_congr_ae
    filter_upwards [domainCutoff_coe Ω hΩ f, domainCutoff_coe Ω hΩ g] with x hf hg
    change inner (𝕜 := ℂ) ((domainCutoff Ω hΩ f : Euclidean d → ℂ) x) (g x) =
      inner (𝕜 := ℂ) (f x) ((domainCutoff Ω hΩ g : Euclidean d → ℂ) x)
    rw [hf, hg]
    by_cases hx : x ∈ Ω <;> simp [hx]
/-- The paper's Euclidean Fourier cutoff P = F⁻¹ 1_Ω F. -/
def fourierProjection {d : ℕ} (Ω : Set (Euclidean d)) (hΩ : MeasurableSet Ω) :
    OrthProjection (FullL2 d) := (domainProjection Ω hΩ).conjugate (paperFourierL2 d)
/-- Fourier transforms the cutoff projection into multiplication by the domain indicator. -/
theorem fourierProjection_transform {d : ℕ} (Ω : Set (Euclidean d)) (hΩ : MeasurableSet Ω)
    (f : FullL2 d) :
    paperFourierL2 d ((fourierProjection Ω hΩ).op f) =
      domainCutoff Ω hΩ (paperFourierL2 d f) := by
  exact (paperFourierL2 d).apply_symm_apply _
end RieszEuclidean

/- Source: RieszEuclidean/MovingComparison.lean -/
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
/-!
# Passing to a moving comparison projection

This is the last analytic limit in Section 6 of the Euclidean manuscript.
Unlike the lattice argument, the comparison projection depends on the parameter.
The hypotheses here explicitly require both limiting families; construction of
those families is a separate obligation recorded in the blueprint.
-/
noncomputable section
namespace RieszEuclidean.OrthProjection

variable {H : Type} [NormedAddCommGroup H] [InnerProductSpace ℂ H]

/-- A common distance bound survives simultaneous strong convergence of both sides. -/
theorem gap_le_of_two_strong_limits
    (P M : ℕ → H →L[ℂ] H) (R Q : H →L[ℂ] H) (γ : ℝ)
    (hP : StronglyConverges P R) (hM : StronglyConverges M Q)
    (hgap : ∀ j, ‖P j - M j‖ ≤ γ) : ‖R - Q‖ ≤ γ := by
  have hγ : 0 ≤ γ := (norm_nonneg (P 0 - M 0)).trans (hgap 0)
  apply ContinuousLinearMap.opNorm_le_bound _ hγ
  intro x
  have hx := ((hP x).sub (hM x)).norm
  change Filter.Tendsto (fun j => ‖(P j - M j) x‖) Filter.atTop
    (nhds ‖(R - Q) x‖) at hx
  apply le_of_tendsto' hx
  intro j
  exact ((P j - M j).le_opNorm x).trans
    (mul_le_mul_of_nonneg_right (hgap j) (norm_nonneg x))

/-- Operator-norm convergence of the comparison family is more than sufficient. -/
theorem gap_le_of_moving_comparison
    (P M : ℕ → H →L[ℂ] H) (R Q : H →L[ℂ] H) (γ : ℝ)
    (hP : StronglyConverges P R)
    (hM : Filter.Tendsto M Filter.atTop (nhds Q))
    (hgap : ∀ j, ‖P j - M j‖ ≤ γ) : ‖R - Q‖ ≤ γ := by
  apply gap_le_of_two_strong_limits P M R Q γ hP _ hgap
  intro x
  exact (ContinuousLinearMap.apply ℂ H x).continuous.tendsto Q |>.comp hM

/-- The Euclidean boundary contradiction after constructing the two limits. -/
theorem moving_comparison_obstruction [CompleteSpace H]
    (Pminus Pplus Mminus Mplus : ℕ → H →L[ℂ] H)
    (Rminus Rplus Q : OrthProjection H) (γ : ℝ) (hγ : γ < 1)
    (hminus : StronglyConverges Pminus Rminus.op)
    (hplus : StronglyConverges Pplus Rplus.op)
    (hMminus : Filter.Tendsto Mminus Filter.atTop (nhds Q.op))
    (hMplus : Filter.Tendsto Mplus Filter.atTop (nhds Q.op))
    (hgapminus : ∀ j, ‖Pminus j - Mminus j‖ ≤ γ)
    (hgapplus : ∀ j, ‖Pplus j - Mplus j‖ ≤ γ)
    (hinclusion : Rminus.range < Rplus.range) : False := by
  exact nested_not_both_gap Rminus Rplus Q hinclusion
    ⟨(gap_le_of_moving_comparison Pminus Mminus Rminus.op Q.op γ
        hminus hMminus hgapminus).trans_lt hγ,
     (gap_le_of_moving_comparison Pplus Mplus Rplus.op Q.op γ
        hplus hMplus hgapplus).trans_lt hγ⟩

end RieszEuclidean.OrthProjection

/- Source: RieszEuclidean/WeakLimits.lean -/
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
/-! Elementary facts about Beurling weak limits. Hull compactness and the
invariant probability measure remain separate blueprint obligations. -/
noncomputable section
namespace RieszEuclidean

variable {d : ℕ}

theorem Separated.translate {δ : ℝ} {Γ : Set (Euclidean d)}
    (h : Separated δ Γ) (z : Euclidean d) : Separated δ (translate z Γ) := by
  intro x hx y hy hxy
  have hne : x + z ≠ y + z := fun heq => hxy (add_right_cancel heq)
  simpa only [dist_add_right] using h hx hy hne

/-- Constant sequences converge in the actual local matching definition. -/
theorem weaklyConverges_const (Γ : Set (Euclidean d)) :
    WeaklyConverges (fun _ => Γ) Γ := by
  intro R hR ε hε
  refine ⟨0, fun j hj => ⟨?_, ?_⟩⟩
  · intro x hx _
    exact ⟨x, hx, by simpa using hε⟩
  · intro x hx _
    exact ⟨x, hx, by simpa using hε⟩

/-- Fixed translations preserve Beurling weak convergence. -/
theorem WeaklyConverges.translate {Γ : ℕ → Set (Euclidean d)}
    {Γ₀ : Set (Euclidean d)} (h : WeaklyConverges Γ Γ₀) (z : Euclidean d) :
    WeaklyConverges (fun j => translate z (Γ j)) (translate z Γ₀) := by
  intro R hR ε hε
  obtain ⟨N, hN⟩ := h (R + ‖z‖) (by positivity) ε hε
  refine ⟨N, fun j hj => ⟨?_, ?_⟩⟩
  · intro x hx hxR
    have hxz : ‖x + z‖ < R + ‖z‖ := (norm_add_le x z).trans_lt (by linarith)
    obtain ⟨y, hy, hxy⟩ := (hN j hj).1 (x + z) hx hxz
    refine ⟨y - z, ?_, ?_⟩
    · simpa [translate] using hy
    · simpa only [dist_eq_norm, show x - (y - z) = x + z - y by abel] using hxy
  · intro y hy hyR
    have hyz : ‖y + z‖ < R + ‖z‖ := (norm_add_le y z).trans_lt (by linarith)
    obtain ⟨x, hx, hxy⟩ := (hN j hj).2 (y + z) hy hyz
    refine ⟨x - z, ?_, ?_⟩
    · simpa [translate] using hx
    · simpa only [dist_eq_norm, show x - z - y = x - (y + z) by abel] using hxy

/-- The common separation constant is retained by a weak limit. -/
theorem WeaklyConverges.separated {δ : ℝ} {Γ : ℕ → Set (Euclidean d)}
    {Γ₀ : Set (Euclidean d)} (h : WeaklyConverges Γ Γ₀)
    (hsep : ∀ j, Separated δ (Γ j)) : Separated δ Γ₀ := by
  intro x hx y hy hxy
  by_contra hbad
  have hdist : 0 < dist x y := dist_pos.mpr hxy
  let ε : ℝ := min (dist x y / 4) ((δ - dist x y) / 4)
  have hε : 0 < ε := lt_min (by positivity) (by linarith)
  have hε₁ : ε ≤ dist x y / 4 := min_le_left _ _
  have hε₂ : ε ≤ (δ - dist x y) / 4 := min_le_right _ _
  let R : ℝ := max ‖x‖ ‖y‖ + 1
  have hR : 0 < R := by dsimp [R]; linarith [le_max_left ‖x‖ ‖y‖, norm_nonneg x]
  have hxR : ‖x‖ < R := by dsimp [R]; linarith [le_max_left ‖x‖ ‖y‖]
  have hyR : ‖y‖ < R := by dsimp [R]; linarith [le_max_right ‖x‖ ‖y‖]
  obtain ⟨N, hN⟩ := h R hR ε hε
  obtain ⟨a, ha, hax⟩ := (hN N le_rfl).2 x hx hxR
  obtain ⟨b, hb, hby⟩ := (hN N le_rfl).2 y hy hyR
  have hab : a ≠ b := by
    intro heq
    subst b
    have ht := dist_triangle x a y
    rw [dist_comm x a] at ht
    linarith
  have hs := hsep N ha hb hab
  have ht₁ := dist_triangle a x b
  have ht₂ := dist_triangle x y b
  rw [dist_comm y b] at ht₂
  linarith

end RieszEuclidean

/- Source: MainResults.lean -/
run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})
/-!
# Implemented result statements and concrete definitions

This compact Comparator reference currently covers the foundational and affine
results only. It does not contain or certify the unfinished geometric main
theorems. Its wrapper proofs use the checked modular library, so the reference
needs neither theorem placeholders nor warning suppressions.
-/
noncomputable section
open MeasureTheory
open scoped ENNReal
namespace RieszEuclidean.Results

/-- Euclidean space in the dimension appearing in the manuscript. -/
abbrev Space (d : ℕ) := EuclideanSpace ℝ (Fin d)

/-- The paper's concrete exponential Riesz basis predicate, written out for review. -/
def HasBasis {d : ℕ} (Ω Λ : Set (Space d)) : Prop := by
  classical
  exact ∃ S : lp (fun _ : Λ => ℂ) 2 ≃L[ℂ] Lp ℂ 2 (volume.restrict Ω),
    ∀ ξ : Λ, (S (lp.single 2 ξ 1) : Space d → ℂ) =ᵐ[volume.restrict Ω]
      fun x => Complex.exp
        (2 * (Real.pi : ℂ) * Complex.I * (inner (𝕜 := ℝ) ξ.val x : ℂ))

/-- An arbitrary invertible affine image of the domain. -/
def affineImage {d : ℕ} (a : Space d) (A : Space d ≃L[ℝ] Space d)
    (Ω : Set (Space d)) : Set (Space d) := (fun x => a + A x) '' Ω

/-- Lemma 2.1 with its actual restriction-to-range definition. -/
theorem projection_gap {H : Type} [NormedAddCommGroup H] [InnerProductSpace ℂ H]
    [CompleteSpace H] (P Q : OrthProjection H) :
    ‖P.op - Q.op‖ < 1 ↔
      ∃ e : Q.range ≃L[ℂ] P.range, ∀ x : Q.range, (e x : H) = P.op x :=
  OrthProjection.gap_iff_rangeIso P Q

/-- Lemma 2.2: strict inclusion of ranges is incompatible with two gaps below one. -/
theorem strict_inclusion_obstruction {H : Type} [NormedAddCommGroup H]
    [InnerProductSpace ℂ H] [CompleteSpace H] (P Q M : OrthProjection H)
    (h : P.range < Q.range) : ¬ (‖P.op - M.op‖ < 1 ∧ ‖Q.op - M.op‖ < 1) :=
  OrthProjection.nested_not_both_gap P Q M h

/-- Beurling weak limits retain a uniform separation constant. -/
theorem weak_limit_separation {d : ℕ} {δ : ℝ}
    {Γ : ℕ → Set (Space d)} {Γ₀ : Set (Space d)}
    (h : WeaklyConverges Γ Γ₀) (hsep : ∀ j, Separated δ (Γ j)) :
    Separated δ Γ₀ := h.separated hsep

/-- Arbitrary affine transport of the concrete synthesis predicate. -/
theorem affine_invariance {d : ℕ} (a : Space d) (A : Space d ≃L[ℝ] Space d)
    (Ω : Set (Space d)) :
    (∃ Λ, HasBasis (affineImage a A Ω) Λ) ↔ ∃ Λ, HasBasis Ω Λ :=
  exists_exponentialRieszBasis_affine_iff a A Ω

/-- The concrete Euclidean Schwartz Parseval pairing underlying the L² extension. -/
theorem fourier_parseval {d : ℕ} (f g : SchwartzMap (Space d) ℂ) :
    (∫ x, Real.fourierIntegral f x * starRingEnd ℂ (Real.fourierIntegral g x)) =
      ∫ x, f x * starRingEnd ℂ (g x) := schwartz_parseval f g

/-- Existence of the actual Euclidean unitary Fourier map and its measurable-domain cutoffs. -/
theorem euclidean_fourier_cutoff (d : ℕ) :
    ∃ U : Lp ℂ 2 (volume : Measure (Euclidean d)) ≃ₗᵢ[ℂ]
        Lp ℂ 2 (volume : Measure (Euclidean d)),
      (∀ f : SchwartzMap (Euclidean d) ℂ,
        (U (f.toLp 2 volume) : Euclidean d → ℂ) =ᵐ[volume] Real.fourierIntegralInv f) ∧
      ∀ Ω : Set (Euclidean d), MeasurableSet Ω →
        ∃ P : OrthProjection (Lp ℂ 2 (volume : Measure (Euclidean d))),
          ∀ f, (U (P.op f) : Euclidean d → ℂ) =ᵐ[volume]
            Ω.indicator (U f : Euclidean d → ℂ) := by
  refine ⟨paperFourierL2 d, paperFourierL2_schwartz d, ?_⟩
  intro Ω hΩ
  refine ⟨fourierProjection Ω hΩ, ?_⟩
  intro f
  rw [fourierProjection_transform]
  exact domainCutoff_coe Ω hΩ _
/-- Schwartz functions are dense in Euclidean L². -/
theorem schwartz_density (d : ℕ) :
    DenseRange (fun f : SchwartzMap (Euclidean d) ℂ => f.toLp 2 volume) :=
  schwartz_toL2_denseRange d
end RieszEuclidean.Results
