#!/usr/bin/env python3
"""Assemble the checked modules; Comparator verifies, it does not generate Lean source."""
from pathlib import Path
import argparse
import hashlib
import json
import re

root = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
modules = {f'RieszEuclidean.{p.stem}': p for p in (root/'RieszEuclidean').glob('*.lean')
           if p.stem != 'ProofAudit'}
order, visiting, done = [], set(), set()

def visit(name):
    if name in done:
        return
    assert name not in visiting and name in modules
    visiting.add(name)
    for dep in re.findall(r'^import (RieszEuclidean\.\S+)', modules[name].read_text(), re.M):
        visit(dep)
    visiting.remove(name)
    done.add(name)
    order.append(modules[name])

for name in sorted(modules):
    visit(name)
order.append(root/'MainResults.lean')
imports, bodies = set(), []
for source in order:
    text = source.read_text()
    imports.update(re.findall(r'^import (Mathlib\.\S+)', text, re.M))
    body = re.sub(r'^import .+\n', '', text, flags=re.M).strip()
    # Lean's auxiliary proof cache is local to a compilation unit and is not
    # stored in .olean files. Reproduce that boundary when concatenating files.
    # This resets only name deduplication, never declarations or kernel checks.
    boundary = 'run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})'
    bodies.append(f'/- Source: {source.relative_to(root)} -/\n{boundary}\n{body}\n')
result = '\n'.join(f'import {x}' for x in sorted(imports)) + '''

/-!
# Standalone Euclidean formalization: implemented components

Generated by scripts/build_standalone.py. No project import is required.
The geometric nonexistence theorems remain pending; MainResults specifies only
the currently proved supporting results. This file is a complete
proof of those statements, not of the entire manuscript.
-/

''' + '\n'.join(bodies)
target = root/'RieszEuclideanStandalone.lean'
hashes = {str(p.relative_to(root)): hashlib.sha256(p.read_bytes()).hexdigest() for p in order}
hashes['RieszEuclideanStandalone.lean'] = hashlib.sha256(result.encode()).hexdigest()
record = json.dumps(hashes, indent=2)+'\n'
if args.check:
    assert target.read_text() == result, 'Stale standalone source'
    assert (root/'standalone/source-hashes.json').read_text() == record, 'Stale extraction hashes'
    print('Standalone extraction matches every source module and the result reference.')
else:
    target.write_text(result)
    (root/'standalone/source-hashes.json').write_text(record)
