#!/usr/bin/env python3
"""Assemble the checked modules; Comparator verifies, it does not generate Lean source."""
from pathlib import Path
import argparse
import hashlib
import json
import re
from check_blueprint import uncomment

root = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
modules = {f'RieszEuclidean.{p.stem}': p for p in (root/'RieszEuclidean').glob('*.lean')
           if p.stem != 'ProofAudit'}
order, visiting, done = [], set(), set()

def visit(name):
    if name in done:
        return
    assert name not in visiting and name in modules
    visiting.add(name)
    for dep in re.findall(r'^import (RieszEuclidean\.\S+)', modules[name].read_text(), re.M):
        visit(dep)
    visiting.remove(name)
    done.add(name)
    order.append(modules[name])

for name in sorted(modules):
    visit(name)
order.append(root/'MainResults.lean')
imports, bodies = set(), []


def close_file_sections(text, source):
    """Close anonymous sections that Lean normally closes at end of file."""
    scopes = []
    for line in uncomment(text).splitlines():
        match = re.fullmatch(
            r'\s*(noncomputable section|section|namespace|end)(?:\s+([\w.]+))?\s*', line)
        if not match:
            continue
        command, name = match.groups()
        if command == 'end':
            assert scopes, f'Unmatched end in {source}'
            _, opened_name = scopes.pop()
            assert name is None or name == opened_name, f'Mismatched scope in {source}'
        else:
            scopes.append((command, name))
    assert all(command != 'namespace' and name is None for command, name in scopes), \
        f'Only anonymous sections may remain open at EOF: {source}'
    return 'end\n' * len(scopes)


for source in order:
    text = source.read_text()
    imports.update(re.findall(r'^import (Mathlib\.\S+)', text, re.M))
    body = re.sub(r'^import .+\n', '', text, flags=re.M).strip()
    # Lean's auxiliary proof and matcher caches are local to a compilation unit and are not
    # stored in .olean files. Reproduce that boundary when concatenating files.
    # This resets only name deduplication, never declarations or kernel checks.
    boundary = ('run_cmd Lean.modifyEnv (Lean.Meta.auxLemmasExt.setState · {})\n'
                'run_cmd Lean.modifyEnv (Lean.Meta.Match.matcherExt.setState · {})')
    # A compilation unit also isolates `open`, scoped notation, local attributes,
    # options, and section variables. An anonymous outer section restores those
    # settings after closing any sections the source leaves open at EOF.
    closing = close_file_sections(body, source.relative_to(root))
    bodies.append(f'/- Source: {source.relative_to(root)} -/\n{boundary}\n'
                  f'section\n{body}\n{closing}end\n')
result = '\n'.join(f'import {x}' for x in sorted(imports)) + '''

/-!
# Standalone Euclidean formalization: implemented components

Generated by scripts/build_standalone.py. No project import is required.
MainResults states proved supporting results, stationary spectral-measure
existence, and the unconditional geometric conclusions of the manuscript.
-/

''' + '\n'.join(bodies)
target = root/'RieszEuclideanStandalone.lean'
hashes = {str(p.relative_to(root)): hashlib.sha256(p.read_bytes()).hexdigest() for p in order}
hashes['RieszEuclideanStandalone.lean'] = hashlib.sha256(result.encode()).hexdigest()
record = json.dumps(hashes, indent=2)+'\n'
if args.check:
    assert target.read_text() == result, 'Stale standalone source'
    assert (root/'standalone/source-hashes.json').read_text() == record, 'Stale extraction hashes'
    print('Standalone extraction matches every source module and the result reference.')
else:
    target.write_text(result)
    (root/'standalone/source-hashes.json').write_text(record)
